spring.application.name=quiz-service

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

#Server Port (Skiljer sig från övriga mikrotjänster)
server.port=8082

#Database config - QuizService databas
spring.datasource.url=jdbc:mysql://localhost:3306/quizServiceDb
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

#Logging
spring.output.ansi.enabled=ALWAYS
logging.level.org.hibernate.SQL=DEBUG

#File upload config (för excell filer)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#Svensk tid
spring.jpa.properties.hibernate.jdbc.time_zone=Europe/Stockholm
spring.jackson.time-zone=Europe/Stockholm
spring.jackson.date-format=yyyy-MM-dd HH:mm

# JWT Configuration
jwt.secret=mySecretKey123456789012345678901234567890
jwt.expiration=86400000
